# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np

# Генерация массива со случайными числами
arr = np.random.uniform(low=0, high=20, size=(4, 7))

# Нормализация массива
a = 1.0 / (np.max(arr) - np.min(arr))
b = -np.min(arr) * a
normalized_arr = a * arr + b

print(normalized_arr)



2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
import numpy as np

# Создание матрицы 8x10 из случайных чисел от 0 до 10
matrix = np.random.randint(0, 10, (8, 10))

# Нахождение индекса строки с минимальной суммой значений
min_sum_index = np.argmin(matrix.sum(axis=1))

# Вывод строки с минимальной суммой значений
min_sum_row = matrix[min_sum_index]

print("Индекс строки с минимальной суммой значений:", min_sum_index)
print("Строка с минимальной суммой значений:", min_sum_row)


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [2]:
import numpy as np

# Одномерные векторы
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Нахождение евклидова расстояния
euclidean_distance = np.linalg.norm(vector1 - vector2, 2)

print("Евклидово расстояние между векторами:", euclidean_distance)


Евклидово расстояние между векторами: 5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
import numpy as np

# Задание матриц A, B и C
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

# Решение матричного уравнения
X = np.linalg.solve(np.dot(A, B), -C)

print("Матрица X:")
print(X)


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows= 1, dtype=np.int32)
print(data[:5])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [14]:
first_col_cut = data[:,1:]
mean = np.mean(first_col_cut,axis=0)
minimum = np.min(first_col_cut,axis=0)
maximum = np.max(first_col_cut,axis=0)
median = np.median(first_col_cut,axis=0)
print("Mean:", mean)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Median:", median)

Mean: [2.16010017e+04 9.05528000e+00]
Minimum: [0 1]
Maximum: [2147483647         39]
Median: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [15]:
q75 = np.quantile(data[:, 1:], 0.75, axis=0)
print("Quantile 0.75:", q75)

Quantile 0.75: [65. 11.]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [9]:
zero_duration_count = np.sum(data[:, 1] == 0)
print("Number of recipes with duration 0:", zero_duration_count)

Number of recipes with duration 0: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [11]:
data[data[:, 1] == 0, 1] = 1
unique_recipes = np.unique(data[:, 0])
print("Number of unique recipes:", len(unique_recipes))

Number of unique recipes: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [16]:
unique_ingredient_counts = np.unique(data[:, 2:], axis=0)
print("Number of unique ingredient counts:", len(unique_ingredient_counts))
print("Unique ingredient counts:",unique_ingredient_counts)

Number of unique ingredient counts: 37
Unique ingredient counts: [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [37]
 [39]]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
filtered_data = data[data[:,2] <=5 ]
print(filtered_data)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
ans8 = np.max(data[:, 2] / data[:, 1]) 
print(ans8)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
arr = data[data[:,1].argsort()][::-1]
print(np.mean(arr[:100,2]))

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [6]:
top10 = data[np.random.choice(data.shape[0],size=10, replace=False)]
print("Top10 randon recieps :\n", top10)

Top10 randon recieps :
 [[405027    495      7]
 [363463     25     11]
 [221165    135      9]
 [220361     30      6]
 [ 70573     20     12]
 [195703     60      8]
 [ 76923     60     13]
 [373485     30     14]
 [104470     15      4]
 [469401     45      9]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [7]:
belo_mean_procentage = np.mean(data[:,2] < np.mean(data[:,2]))*100
print(belo_mean_procentage)

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [8]:
simple = (data[:,1]<=20)&(data[:,2]<=5)
simple_data = np.column_stack((data,simple))
simple_data

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [9]:
np.mean(simple_data[:,3]==1)*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.